android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.java.installations.paths=/usr/lib/jvm/jdk-25.0.1-oracle-x64
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.javaCompile.suppressSourceTargetDeprecationWarning=true

